### ISSUE TITLE
ユーザ名をクリックしたらユーザページへ飛んでほしい

### ISSUE THREAD

**Issue by hidao80** [hidao80/mastogetter#19]
ユーザ名をクリックしたらユーザページへ飛んでほしい。
今はユーザ名にリンクが貼られていない。

**Comment by blhsrwznrghfzpr** [comment]
対応中です 💪
@yume-yu `a` タグを挟み込むので、スタイルの変更が必要になりますが、後でまっつんさんにお願いした方がよいでしょうか？

**Comment by yume-yu** [comment]
@blhsrwznrghfzpr 
いいかんじ(体感)にできそうであればスタイルまで変えちゃって大丈夫ですよ!
https://github.com/hidao80/mastogetter/blob/bdf90e3566b9708a53d07f0d97c3880613b6f720/css/style.css#L158-L161
このあたりの対象を修正すれば行けそうです。reset cssが聞いていれば下線の無効化とかはいらないかも?です
