### ISSUE TITLE
作成済みパーマリンクを読み込み、トゥート追加するとパーマリンクが未完全になる

### ISSUE THREAD

**Issue by KEINOS** [hidao80/mastogetter#24]
## TL;DR

発行済みパーマリンクに追加されまてん。

- Chrome v79.0.3945.88, macOS Mojave

### 再現方法

> `https://hidao80.github.io/mastogetter/p.html?i=https://qiitadon.com&t=103422588059240282,103422611462024633,103422832136585995,103423069795875723,103423087302441993,103423091368850281,103423137489223891,103423155290513020,103423839710682996`

上記パーマリンクを、[ますとげったー](https://hidao80.github.io/mastogetter/)の「パーマリンク読込」に貼り付け、追加したいトゥート
`https://qiitadon.com/web/statuses/103433642368719830`
を「トゥートID or URL」に貼り付けました。

「プレビュー」でちゃんと表示されたので、「プレビュー中のトゥートを追加」したところ、右側ペイン（トゥート一覧）の最後尾に追加されました。

しかし、右側ペイン上部にある「パーマリンク」の input フィールドが最後に追加したトゥート ID のみになってしまいます。

> `https://hidao80.github.io/mastogetter/p.html?i=https://qiitadon.com&t=103433642368719830,`

２連続「プレビュー中のトゥートを追加」を押下すると、同じトゥートが追加されるので、リセットして追記しているわけではないようです。

> `https://hidao80.github.io/mastogetter/p.html?i=https://qiitadon.com&t=103433642368719830,103433642368719830,`

「パーマリンク読込」の「読込」ボタン押下時は、右側ペイン上部の input フィールドに既存のパーマリンクは流し込まれているようなので、初回「プレビュー中のトゥートを追加」時に消えてしまいます。

### 考えられる原因

おそらく、パーマリンク読込ボタンの `loadPermalink()` 時に `genPermalink()` でパーマリンク作成後、`toot_list` もちくは `card_list` に追加していないからなのかな、と思います。

https://github.com/hidao80/mastogetter/blob/435b615222fe9a606bf15fff8469ee55aa567726/js/index.js#L81-L126

**Comment by hidao80** [comment]
@KEINOS oh… 完全にそうですね…
card_list を更新してないのが原因でしょう。
`genPermalink()` のバグですね。直しましょう。

**Comment by KEINOS** [comment]
パッチりんこ！

https://hidao80.github.io/mastogetter/p.html?i=https://qiitadon.com&t=103422588059240282,103422611462024633,103422832136585995,103423069795875723,103423087302441993,103423091368850281,103423137489223891,103423155290513020,103423839710682996,103436705310416669,
