### ISSUE TITLE
編集ページがスマートフォンでの表示に完全に対応していない

### ISSUE THREAD

**Issue by yume-yu** [hidao80/mastogetter#30]
ブラウザの表示を信用しすぎたので要修正
![Screenshot_20200106-213813](https://user-images.githubusercontent.com/30368684/71818831-63dbce80-30cd-11ea-89f9-12a3b569ba0f.png)

**Comment by yume-yu** [comment]
申し訳ないことに #38 はrefactoringを名乗っているのにこの変更を含んでいます...

**Comment by hidao80** [comment]
@yume-yu この Issue は解決済みで、close していいって事でしょうか？

**Comment by yume-yu** [comment]
@hidao80 close忘れていました!閉じます 💪
