### ISSUE TITLE
パーマリンクを短縮 URL で

### ISSUE THREAD

**Issue by KEINOS** [hidao80/mastogetter#33]
https://hidao80.github.io/mastogetter/ は `*.github.io` ドメインなので https://git.io/ の短縮 URL が使える。パーマリンクを短縮 URL で発行したらどうか。

https://git.io/Jej7j

- `cURL` でフォームを送信する例

```bash
curl -s -L -i https://git.io -F "url=https://hidao80.github.io/mastogetter/p.html?i=https://qiitadon.com&t=103422588059240282,103422611462024633,103422832136585995,103423069795875723,103423087302441993,103423091368850281,103423137489223891,103423155290513020"
```

- レスポンスヘッダの `Location` で短縮 URL を取得できる。

```shellsession
$ curl -s -L -i https://git.io -F "url=https://hidao80.github.io/mastogetter/p.html?i=https://qiitadon.com&t=103422588059240282,103422611462024633,103422832136585995,103423069795875723,103423087302441993,103423091368850281,103423137489223891,103423155290513020" | grep Location
Location: https://git.io/Jej7j
```

- パーマリンクに固有名を付ける例

```shellsession
$ curl -s -L \
$  -i https://git.io \
$  -F "url=https://hidao80.github.io/mastogetter/" \
$  -F "code=mastogetter" | grep Location
Location: https://git.io/mastogetter
```

**Comment by KEINOS** [comment]
### 進捗

**結論**から言うと git.io からの取得は **Javascript だけで完結させるのは難しそう**です。

**理由**は、git.io 側が `Access-Control-Allow-Origin: *` をレスポンス・ヘッダに含んでいないため、ブラウザ（Chrome）の **CORS 制限により Javascript 側にヘッダ情報をくれない**からです。

以下は git.io に Javascript から POST リクエストした際のデベロッパー・ツールの内容です。ちゃんとレスポンスが返ってきているのがわかります。

<kbd><img width="100%" alt="スクリーンショット 2020-01-08 9 36 33" src="https://user-images.githubusercontent.com/11840938/71941099-f37f9b00-31fb-11ea-97ef-b9b2ff92253a.png"></kbd>

しかし、コーンソールを見るとエラーでブロックされています。

<kbd><img width="100%" alt="スクリーンショット 2020-01-08 9 50 55" src="https://user-images.githubusercontent.com/11840938/71941327-a8b25300-31fc-11ea-9b5b-6bf5b7a8b7af.png"></kbd>

`fetch()` で `mode: 'no-cores'` を設定するとエラーは出なくなるのですが、`Access-Control-Allow-Origin` がヘッダにないため[ブラウザの制限](https://stackoverflow.com/a/54906434/12102603)により取得できません。

**回避策**としては：

1. フォームを用意しておいてボタンを押したら git.io に POST し転送させる。
2. プロクシ・サーバーを用意する。

おそらく１番の転送が簡単で、転送後は `https://git.io/***` の `***` 部分だけが表示されるページに転送されました。

2 は、Qithub のサーバーを使ってもいいのですが、Issue #22 の件もあるので、まずは１番で実装したいと思いますが、いかがでしょう？

**Comment by hidao80** [comment]
開発ブランチで止めておくつもりが、`gh-pages`ブランチにマージしてしまいました。マジで。

「やってもうた、短縮URL機能リリースしてもうたで工藤！」by ひだお
https://qiitadon.com/@hidao/103447395722195785

本チケットを解決とします。

スタイルは別チケットで対応します。🙇‍♂️

**Comment by KEINOS** [comment]
4750bd7 で `revert` されていたんですね。気づかなかった... ただ、戻すのが正しいと思います。

**Comment by hidao80** [comment]
@KEINOS 申し訳ないです。一言ことわりを入れるのが筋でした…🙇‍♂️
開発ブランチでレイアウトが整ったら、`master`に上げ直します！
正直、スマンかった…

**Comment by KEINOS** [comment]
ノープロです！一旦 design-dev と feature-dev の足並みを揃えましょう。
整ったら master でも良いと思います。今日はテンポが速いので大変ですね。
