### ISSUE TITLE
「カーソルを合わせてヒントを表示」のヒントが表示されない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [hidao80/mastogetter#39]
環境： Windows10+Chrome
確認したバージョン： バージョン1
確認時のコミットハッシュ： 1e8fadb0883761f3638fb3d0b5adb228d961731a

おそらく CSS の
```css
	position: absolute;
	bottom: 200%;
```
によって画面外に吹っ飛んでいそう

https://github.com/hidao80/mastogetter/blob/1e8fadb0883761f3638fb3d0b5adb228d961731a/css/style.css#L201-L206

**Comment by yume-yu** [comment]
@yume-yu 対応中です :muscle:

**Comment by hidao80** [comment]
@blhsrwznrghfzpr @yume-yu 
対応済みコミットをマージしましたので、本チケットを解決とします！
