### ISSUE TITLE
入力画面のデザインが冴えない

### ISSUE THREAD

**Issue by hidao80** [hidao80/mastogetter#4]
入力画面のフォームに対してスタイルを指定していないため、デザインが冴えないのを改善したい。

**Comment by yume-yu** [comment]
やってみました。cssのリファクタリングはご容赦を...
https://github.com/yume-yu/mastogetter/commit/b2c779291b4d257f3e355382fac9c47142d32573

![スクリーンショット 2020-01-06 3 38 10](https://user-images.githubusercontent.com/30368684/71784417-bf0eb200-3036-11ea-98f7-63361c72e56d.png)

ついでに@mediaでレスポンシブ?っぽくなってます
![スクリーンショット 2020-01-06 3 38 51](https://user-images.githubusercontent.com/30368684/71784416-bc13c180-3036-11ea-9b1d-9e3ac25dd974.png)

**Comment by hidao80** [comment]
@yume-yu おお！めちゃめちゃイイ感じですね！
一部機能追加に伴いプレースホルダ等変えてますので、html・js 変更時にはこちらの最新版をマージしてから修正していただけるとありがたいです！

**Comment by hidao80** [comment]
@yume-yu おおっと、マージするのはプルリク出す時でいいですよ！

**Comment by yume-yu** [comment]
わかりました、ハイパーQiitaインスパイアの調整がすんだらプルリク前にマージします

**Comment by yume-yu** [comment]
@hidao80 design-developを閉じられたみたいですが、masterへのプルリクでいいですか?

**Comment by hidao80** [comment]
@yume-yu マージのタイミングで閉じてしまったようですね…
design-develop を切り直すので暫しお待ちを。

**Comment by hidao80** [comment]
@yume-yu ブランチ切りました。
プルリクよろしくお願いします。

**Comment by hidao80** [comment]
修正マージが追加で来るようですので、本 Issue はまだクローズしません。

**Comment by hidao80** [comment]
さすがにこの状態で「冴えない」とは言わせないので、本 Issue をクローズします。
