### ISSUE TITLE
コンソールに toot_ids 未定義エラー

### ISSUE THREAD

**Issue by KEINOS** [hidao80/mastogetter#41]
「まとめを読み込む」ボタン押下時にコンソールに `Uncaught ReferenceError toot_ids is not defined` エラーが出ます。

<kbd><img width="100%" alt="スクリーンショット 2020-01-08 14 09 31" src="https://user-images.githubusercontent.com/11840938/71952051-90ecc600-3220-11ea-90af-3e020fda04ec.png"></kbd>

## 原因

「まとめを読み込む」ボタンの関数内で、グローバルのつもりで `toot_ids` を見に行っている。

https://github.com/hidao80/mastogetter/blob/1e8fadb0883761f3638fb3d0b5adb228d961731a/js/index.js#L65-L73

## 対策

[common.js](https://github.com/hidao80/mastogetter/blob/1e8fadb0883761f3638fb3d0b5adb228d961731a/js/common.js) で、`card_list` と同じようにグローバル空間で宣言しておく。

https://github.com/hidao80/mastogetter/blob/1e8fadb0883761f3638fb3d0b5adb228d961731a/js/common.js#L1-L2

PR #40 に追い PUSH で一緒に直しておきます。

**Comment by hidao80** [comment]
@KEINOS それ、こういうことですね。
```
function loadPermalink() {
	const permalink = $("load").value;
	const permalink_str = {"i": permalink.split("?i=")[1].split("&")[0],
						"t": permalink.split("&t=")[1]};
	const permalink_obj = decodePermalink(permalink_str);

	showCards(permalink_obj);
	//genPermalink(toot_ids.join(","));　↓ パーマリンクオブジェクトの toot_ids 配列を使う
	genPermalink(permalink_obj.toot_ids.join(","));
}
```

**Comment by KEINOS** [comment]
PR #44 で対応しています。
