### ISSUE TITLE
まとめを複数回読み込むと表示とpermalinkが合わなくなる

### ISSUE THREAD

**Issue by paihu** [hidao80/mastogetter#43]
症状: まとめを複数回読み込んで、permalinkをコピーすると、最後に読み込んだまとめと同じものになる。(すでに存在しているtootが存在しないかのように振る舞う)

原因: まとめを読み込むと、リストの後ろに追加されるけれど、
permalink的には、既存のものがなかったことになって、読み込んだものだけになってしまっている。

対策:
* 読み込んだ際に表示を一旦クリアし、仕様とする。
* card_list に読み込んだ toot_ids を追加する。

**Comment by hidao80** [comment]
#41 で言及している不具合が原因かもしれない…
https://github.com/hidao80/mastogetter/issues/41#issuecomment-571933642

**Comment by KEINOS** [comment]
PR #44 で対応しています。
