### ISSUE TITLE
まとめの読み込み以外からの個別追加がドラッグ＆ドロップできない

### ISSUE THREAD

**Issue by KEINOS** [hidao80/mastogetter#49]
### 現象

初回作成時、プレビューしてから追加するとトゥートがドラッグ＆ドロッペないです。既存のまとめを読み込んでからだとできます。

### 原因

追加時の `addCard()` 内で `appendChild()` する際に `attribue` に `draggable` ＆イベントリスナーを追加していないため。

https://github.com/hidao80/mastogetter/blob/6410e904126bc8b8e3bf0bd5b91c89c610c7e879/js/index.js#L43-L52

### 対応策

１カード（１トゥート）の要素に以下を追加する関数を用意する。

https://github.com/hidao80/mastogetter/blob/6410e904126bc8b8e3bf0bd5b91c89c610c7e879/js/common.js#L102-L106

これにより、以下の件（#46）も対応が楽になると思います。

> #mastogetter の draggable 、表示用ページの方でもモリモリ順番変えられるんだけどええんか……？
> https://qiitadon.com/web/statuses/103447056096591220 @ Qiitadon より

**Comment by hidao80** [comment]
@KEINOS 表示用ページの方でもりもり順番変えられるのはまた別の関数`showCards()`を使っているためだと考えています。
`showCards()`は既存まとめ読込みと表示用画面の読込みで利用され、プレビューからまとめリストへ登録するときのみ`addCard()`を使っています。

要領悪いのはわかってるんですけど、 #46 は別件じゃないかなぁ…と考えています。🤔

**Comment by KEINOS** [comment]
@hidao80 

言葉が足りませんでした。イベントリスナー追加を関数化して、`showCards()` で使うのではなく `addCard()` で使えば、 #46 も解決するかも、という意味でした。

**Comment by hidao80** [comment]
@KEINOS なるほど！ そういう意味だったら`addEventListener`つけるところを関数化できそうですね！ 納得。
