### ISSUE TITLE
追加済みの toot を削除できるように

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [hidao80/mastogetter#51]
URL から物理的に id を消す方法で削除できなくは無いですが、
編集ページで削除ができるようになってほしい。

追加された toot が最下段に追加されるため、目視で追加されたかがわかりにくく、
複数回同じ toot を追加してしまったので。

**Comment by KEINOS** [comment]
同名の Issue があった気がするのですが、気のせいだったようです。

私も削除できるに 👍

**Comment by hidao80** [comment]
@blhsrwznrghfzpr 編集ページというのは`index.html`の右半分のことでしょうか？
`index.html`の右半分のカード（トゥート）をダブルクリックすると、当該カードが消え、パーマリンクが更新されます💪

…違う？

**Comment by blhsrwznrghfzpr** [comment]
@hidao80 
> `index.html`の右半分のカード（トゥート）をダブルクリックすると、当該カードが消え、パーマリンクが更新されます💪

ぜんぜん気づきませんでした……
すでにある機能だったんですね💦
解決したのでこの issue は close します

**Comment by yume-yu** [comment]
わかりやすく X みたいな削除のボタンをつけたり消せることを示すアイコンを付けたり、tipsマークを付けたりするのはありですね

**Comment by hidao80** [comment]
仕様策定とドキュメント整備と開発がケイオスと化し、制御不能になっている…（ダメPM）
