### ISSUE TITLE
ユーザー名が正しく表示されない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [hidao80/mastogetter#52]
# 現象
インスタンス名が `https://hogedon.com` のときに、トゥートID or URLに `https://hogedon.com/web/statuses/012345678901234567` の形式で toot を取得すると、
その toot が他所のインスタンスの toot でも、
ユーザー名が `@username@hogedon.com` に固定されてしまっています。

# 原因
https://github.com/hidao80/mastogetter/blob/4750bd7571272b8292050be20323bf118aa8c234/js/common.js#L96
にて、入力されたインスタンス名を表示にしようしていますが、
おそらく API レスポンスから正しい値を取得する必要があります。

**Comment by blhsrwznrghfzpr** [comment]
インスタンス qiitadon.com から他所のインスタンスの toot を取ると
`account.acct` が `username@remote.instance` のようになってて使えそうだけど、
今度は qiitadon.com インスタンスの `account.acct` が `username` のみになってしまう…

**Comment by hidao80** [comment]
@blhsrwznrghfzpr **仕様です**（つよき）
現段階では、「トゥートID or URL」テキストボックスでは**インスタンスを判別していません**。

「トゥートID or URL」テキストボックス利用時は左隣の「インスタンス名」欄に別途インスタンスのURLを入力してください。
「インスタンス名」テキストボックスのデフォルト値は「https://qiitadon.com」です。
![image](https://user-images.githubusercontent.com/8155294/71992146-4eef6e80-3278-11ea-887a-cf2909765204.png)
改善案、プルリク募集中です。#37 も見てね。

**Comment by hidao80** [comment]
@blhsrwznrghfzpr あ゛あ゛あ゛そういうことか！
まとめ表示画面で全てのユーザのインスタンスが`userid@qiitadon`になるということですね！
**それは純然たるバグ**です。直しましょう。

**Comment by yumetodo** [comment]
MastodonのTLから来ました。

個人的には`account.acct`を見るよりは`url`からインスタンス名引っ張るほうがいいんじゃないかという気がしています。

**Comment by hidao80** [comment]
と思ったけど、FTLに流れているものは**当該インスタンスに保存されているので、「userid@当該インスタンス」が付くのが正常な動作**です。

ぜんぜんわからない。俺は雰囲気で mastodon をやっている。

**Comment by yumetodo** [comment]
@hidao80 それは自分の所属インスタンス視点での話であって、mastogetterとしてどうするかは別問題でしょう

**Comment by blhsrwznrghfzpr** [comment]
とりあえずURLなどからインスタンス名を引っ張る方針でPR考えてみます

**Comment by hidao80** [comment]
@yumetodo 現在、mastogetter ではまとめ情報を管理する URL の get パラメータに1つしか インスタンス URL を持つことが出来ません。これは現段階の仕様です。

たしかに、mastogetter としてどうするかは別問題ですが、解決方法の見当もされていないのが現状です。
本 Issue で解決したい問題だと考えています。。

**Comment by KEINOS** [comment]
んんん？？ `@KEINOS@pawoo.net` ？？

そのアカウントあるけど、そこからトゥートしとらんのですが、どうなってんの？！

と思って検証してみたら、そういうことか。理解。

<kbd><img width="647" alt="スクリーンショット 2020-01-09 1 00 32" src="https://user-images.githubusercontent.com/11840938/71994283-d1c5f880-327b-11ea-8341-3df6239a28df.png"></kbd>

Mastodon のバージョン互換もありそうだから、力技を使う方向なのかしら。となるとリクエスト数が多くなりそうな気配。

**Comment by yumetodo** [comment]
https://github.com/tootsuite/mastodon/blob/a6269b2f83e3eed1a8ab545f5756cd7b582075f5/spec/helpers/accounts_helper_spec.rb#L57-L65

とおもったんだけど、`acct`についてのテスト見てたらちょっと首かしげてます。(見てるところが違う・・・？

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/71994717-9a0b8080-327c-11ea-9e95-6f72d7cf7136.png)
えっ、ここをくっつけようって話なんですがリクエスト数とか

>現在、mastogetter ではまとめ情報を管理する URL の get パラメータに1つしかインスタンス URL を持つことができません。これは現段階の仕様です。

ってなんか話がすれ違っている・・・？

**Comment by yumetodo** [comment]
```js
      let acct = account.get('acct');

      if (acct.indexOf('@') === -1 && localDomain) {
        acct = `${acct}@${localDomain}`;
      }

      displayName = <bdi><strong className='display-name__html' dangerouslySetInnerHTML={{ __html: account.get('display_name_html') }} /></bdi>;
      suffix      = <span className='display-name__account'>@{acct}</span>;
```

https://github.com/tootsuite/mastodon/blob/59fd622adc18cb094146f7cda1025782d505404e/app/javascript/mastodon/components/display_name.js#L73-L81

あっ

**Comment by yumetodo** [comment]
https://github.com/fedibird/mastodon/blame/b8514561394767a10d3cf40132ada24d938c1680/spec/helpers/statuses_helper_spec.rb
みてて気がついたけど

https://github.com/tootsuite/mastodon/pull/8011
で仕様変わった・・・？

**Comment by KEINOS** [comment]
https://paiza.io/projects/BJFF9fHVUIyP6SL1xNromA @ paiza.IO

上記で、複数インスタンスの実際の API のレスポンスを見たところ、`account` の `acct` と `display_name` を使うのが良い気がする。

**Comment by yumetodo** [comment]
あーびっくりした、`acct`って言われて。

なんかbreaking changeが割と最近入っている感もあるし

>https://mastodon.cardina1.red/@lo48576/103448649823505013
> あー表示だから変えてまえ！ で変わったタイプの…… (つらそう)
>
>ActivityPub 自体は @local@example.com 形式のアカウント表示を規定してないから、独自 API に頼るしかないんですね……
それにしても API の破壊的変更はひどい

みたいな指摘もあるので

```js
<div class="box"><a class="display-name" href="${obj.account.url}" target="_blank">${obj.account.display_name}<span>@${obj.account.username}@${(new URL(obj.url)).hostname}</span></a>
```

みたいな感じでいいのでは。

![image](https://user-images.githubusercontent.com/10869046/71999314-8532eb00-3284-11ea-9b40-48dd03212826.png)

対応ブラウザ問題なければPR投げますよ
```

**Comment by hidao80** [comment]
@yumetodo 明文化はしていませんが、IE と旧 edge は対応外で開発進めているので勧めてくださるとありがたいです！ PR お待ちしています！
