### ISSUE TITLE
URLにTooTの情報を列挙すること自体に限界がないか？

### ISSUE THREAD

**Issue by yumetodo** [hidao80/mastogetter#55]
Activity Pubの仕様上、Aインスタンスにいるaさんの投稿は任意のインスタンスが知っているとは限りません。

現状どのインスタンスから情報を取ることを試行するかはインスタンス名の部分に入れたたった一つのインスタンスに限定されていますが、これだとそのインスタンスが知っている投稿しか取得できないわけです。

購読(mastodon的にはフォロー)やリブログ(mastodon的にはブースト)を活用して**どこか単一のインスタンスはまとめたいすべての投稿を知っている状態にしろとまとめるユーザーに求める**(現状)ならそれでもいいのですが、そうでない場合は投稿ごとにどのインスタンスに問い合わせるかを保持しなくてはいけません。

ここで、permlinkに問い合わせるべきすべてのインスタンスのリストを含めなければならなくなります。

URLの長さは制限はないとはしつつも2000文字を超えるべきではないとされています。domain 名の最大長は 253文字 (RFC1035)です。つまり最悪値でわずか10の投稿をまとめただけでURLが2000文字を超えるということになります。

情報の保持をURLではなくgistなりpastebinなりどこかそういう外部サービスに依存するか鯖をたてるかしなければ現実的にはなくなります

この辺をどう考えているかお聞きしたいです。

1. どこか単一のインスタンスはまとめたいすべての投稿を知っている状態にしろとまとめるユーザーに求める(現状)
2. N個のインスタンスに問い合れば(N<9程度?)まとめたいすべての投稿を誰かは知っている状態にしろとまとめるユーザーに求める ~~(#37 の実装は面倒くさくなりそう)~~(関係なかった)
3. 各投稿ごとにどのインスタンスに問い合わせるかを保持する
    1. URLで頑張る→圧倒的死
    2. 外部サービスに依存
    3. 自鯖を建てる
    4. まとめ主はMastodonの垢を持っていると仮定してTooTに必要な情報を保持する→TLが荒れる
4. その他

**Comment by yume-yu** [comment]
ここは自分の想像なんですが、自分の観測範囲で見えるものをまとめることを想定したサービスなので、「まとめるのに使った(≒自分が所属している)インスタンスからまとめたいものが見えない)」は想定されていないのだと思います。
パーマリンクの件については前にひだおさんが書いてたtootをまだ掘出せていないのですが、外部にデータを置かないのは「githubpagesで完結させる」ってコンセプトで作ってたからだったと記憶しています。

**Comment by hidao80** [comment]
@yumetodo 回答が遅くなり申し訳ありません。

さて、現在の mastogetter の目標は Activity Pub で連携するすべてのインスタンスを単一のスレッド状の status の並びにするものでは**ありません**。
よって、まとめ用インスタンスを要求もしませんし、それを望んではいません。

また、誰にも聞かれていないので公開情報ではありませんでしたが、開発開始時のコンセプトが**ストレージを利用せずに使用・設置できる**ことであるため、「自鯖を立てる」ことも致しません。

ですので、ご提案いただいた結末の中では「URLで頑張る→圧倒的死」を**積極的に支持します**。

本リポジトリは、もともと「toggetter 相当ものが Mastodon にはないのは技術的な問題があるからなのか」という個人的興味を探究する目的から始まったものですので、Mastodon における togetter の互換サービスを目指してはいません。
コミッターをしてくださる方々の中にも togetter の互換製品を作っているのかと誤解を与えていたのなら、この場でそうではないことを釈明しなければなりません。

というわけで、本 Issue への回答としましては「URL だけでは限界があることを承知で始めているし、今のところ方針を変更する予定はない」ということになります。

リポジトリ名がコミッターの方々や将来の利用者にとって害があるようでしたら改名もやぶさかではありません。

長文になりましたが、ご理解いただければ幸いです。

**Comment by yumetodo** [comment]
了解しました！

**Comment by KEINOS** [comment]
個人的に URL の限界に挑戦した、まとめを見てみたい気もします。
