### ISSUE TITLE
`feature-dev` `design-dev` ブランチの `master` 統合

### ISSUE THREAD

**Issue by KEINOS** [hidao80/mastogetter#63]
現在、どのブランチが皆さん的にベストな状態になっているのかわかりまてん。

https://github.com/hidao80/mastogetter/issues/54#issuecomment-572590606 の `gh-pages` `master` ２本立て化のステップとして `DEV` 系ブランチを削除して減量して欲しいです。

もし、その作業で消えてしまったものが出ても「消せらセラ」でまた皆んなで直すということで。

👍 ×4 以上 or @hidao さんの裁量で判断願います。

**Comment by yumetodo** [comment]
現状masterから遠いのって @yume-yu さんのfetch使うように書き換えるやつだけだと思うんですが

**Comment by yume-yu** [comment]
@yumetodo すみませんそのブランチを消し忘れていました 🙇 
forkにグラフ的には`design-dev` `feature-dev`は消しても大丈夫そうなので、該当ブランチを削除します。

**Comment by yume-yu** [comment]
`feature-dev`はすでに閉じられていたので、`design-dev`を閉じました 👍

**Comment by KEINOS** [comment]
> feature-devはすでに閉じられていた

？？ `design-dev` は消えましたが `feature-dev` がまだおるようです。（2020/12/10 14:00 現在）

<kbd><img width="100%" alt="スクリーンショット 2020-01-10 13 56 48" src="https://user-images.githubusercontent.com/11840938/72127001-7d249980-33b1-11ea-8813-72a3e760e3d3.png"></kbd>

@yume-yu 再オープンの権限ないので、オープンお願いしまーす。

**Comment by yume-yu** [comment]
@KEINOS isuueのクローズと勘違いしてました:man_bow:
macの前に戻ったら消しておきます

**Comment by KEINOS** [comment]
> 再オープンの権限ないので、オープンお願いしまーす。

Issue の再オープンって Close した人でないとできないんでしたっけ？

もすかして @yume-yu さん特権ユーザーになった系で、ブランチも消せる系で、Issue ロックもできるようになっちゃった系？

**Comment by yume-yu** [comment]
@KEINOS 再オープンの件はわからないですが、UI面担当ということで権限もらいました :muscle:

**Comment by KEINOS** [comment]
> @yume-yu 
> 権限もらいました 💪

おおっ！おめでとうございます！ブランチも `master` `gh-pages` のみなったことを確認いたしました！

スッキリンこです
