### ISSUE TITLE
[投票] 作業ブランチ名の命名にはルールを設けるべきか

### ISSUE THREAD

**Issue by KEINOS** [hidao80/mastogetter#65]
#54 の「CONTRIBUTING.md のファイルの設置」とは関係がないので新たに本 Issue を立てました。

## 議題

以下をこの Issue で議論にしたいと思います。

1. そもそも作業ブランチ名に命名ルールを設ける必要があるのか
2. 設ける場合は「ブランチの命名ルール」

議題 1 に関しては以下のリアクションでお願いします。<sup>（× 5 以上 or 土曜 01/11 の昼の最多で決定です）</sup>

👍 = 設けた方がいい
👎 = 設けなくてもいい
👀 = 見つめていたい
🚀 = がんばってモチベあげて
🎉 = パーリーピーポー
😕 = そのノリも意味もよくわかりません

## 叩き台の初回内容と意図

叩き台では、「推奨」するスタイルとして以下をあげました。（https://github.com/hidao80/mastogetter/pull/64/commits/18a59306c8d245df4462e3b7bc8ed3be797f9636#diff-6a3371457528722a734f3c51d9238c13R32-R43 より）

---

- 推奨するブランチ名の付け方（`[]` は任意です）
    - `issue`-`<Issue番号>`-`<担当者名>`[-`<作業概要>`]
        -  特定 Issue の対応を行う。
        - Issue の一部の作業である場合は、作業の概要がわかる名前を付けてください。
    - `issue`-`<Issue番号>`[-`<作業概要>`]
        -  担当者名を付けない場合は「他のコラボレーターからも差し込みをして欲しいブランチ」である意味になります。
        - Issue の一部の作業である場合は、作業の概要がわかる名前を付けてください。
    - `typo`-`<担当者名>`
        - 単純な誤字脱字の修正する。
    - `refactor`-`<担当者名>`[-`<対象>`]
        - [リファクタリング](https://ja.wikipedia.org/wiki/%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0))をする。
            - 特定ファイルのリファクタの場合は、対象がわかる名前を付けてください。
---

叩き台で「ブランチ名に担当者名はいらないのではないか」という意見 https://github.com/hidao80/mastogetter/pull/64#issuecomment-572845728 をいただきました。実は、**叩き台に間違いがありまして、担当者名は任意**のつもりでした。

```diff
- `issue`-`<Issue番号>`-`<担当者名>`[-`<作業概要>`]
+ `issue`-`<Issue番号>[`-`<担当者名>`-`<作業概要>`]
```

この `<担当者名>` を付ける・付けないですが、

1. `<担当者名>` あり：「作業ブランチへの他者コミットを希望している」という意思表示
2. `<担当者名>` なし：「レビューまで俺にまかせておくれ」

にしたいと考えました。

基本的に「PR を投げた人が１人で作業するもの」というのはわかっています。しかし LTL や今までのやりとりを見て、このリポジトリにおいては以下を念頭におかないといけないと思います。

- GitHub でコラボったことない
- 作業フローが各々慣れたものと違う
- コミット履歴をトレースするの面倒
- 本業もあるので、なかなか PR を仕上げられない
- 叩き台は作ったからあとは任せた
- ちっ何やってんだよ。俺にやらせてみな。ほらよっ。じゃな
- 進捗確認箇所が多い（ LTL, 特定トゥートのスレッド, Issue など）

そういう意味で、「ブランチ名を一見して条件がわかるといいのに」と思い、叩き台に記載しました。

ただ ... ここまで書いておいて何ですが、ブランチ名よりは [PR 時のタイトルの方が大事](https://github.com/hidao80/mastogetter/pulls)なんじゃね？と思ってきました。本文に「途中コミットキボンヌ」と書いておけばいいんだし。ブランチ名いらないってそういうことだったのか。とほほ。とりあえず土曜の~~夜まで意見募集~~お昼に決定しまーす。

**Comment by yumetodo** [comment]
もっというとbranchってmeregeしたあとは消すので後で辿れない情報であるに対して、コミットメッセージは辿れるのでそっちをちゃんと規定するほうが労力としては見合うのかなと思います。
[js-primer/CONTRIBUTING.md at master · asciidwango/js-primer#コミットメッセージ規約](https://github.com/asciidwango/js-primer/blob/master/CONTRIBUTING.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E8%A6%8F%E7%B4%84)
こういうやつ

**Comment by KEINOS** [comment]
@yumetodo 

確かに、ブランチなんかよりコミットメッセージの書き方を擦り合わせた方がいいですね。[上記を参考](https://github.com/asciidwango/js-primer/blob/master/CONTRIBUTING.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E8%A6%8F%E7%B4%84)に、コミットメッセージの規約も盛り込みたいと思います。

**Comment by KEINOS** [comment]
👎 がまだ 4 ですが、土曜の昼を待たずにとりあえず**ブランチ名のルールは否決**（CONTRIBUTING.mdには含めない）としたいと思います。

なので、一旦この Issue はクローズし 💪 ！

なお、モリモリの CONTRIBUTING.md より、ミニマムな状態から始めたいと考えています。おいどん基本的に情報過多な書き方をする癖があるので...
