### ISSUE TITLE
local serverを指定してしまってnpm script化したほうがいいのではないか

### ISSUE THREAD

**Issue by yumetodo** [hidao80/mastogetter#66]
file://だとCORSとかの関係で扱いに困るので適当なlocal serverを選出したほうがいいのではないかと思いました

ref:
- https://twitter.com/yumetodo/status/706071299508973568
- https://qiitadon.com/@blhsrwznrghfzpr/103456997228914696

候補としては

- https://www.npmjs.com/package/koko
- https://www.npmjs.com/package/@js-primer/local-server

など？webpack使ってないので軽量なやつで十分ですし。(後者のほうがメンテされていそう)

npm scriptを書いて`npm run start`とかするとブラウザで見れるようにするのをイメージしてます。

**Comment by KEINOS** [comment]
確かに CORS は悩むところです。

ただ local server の環境構築ファイルもリポジトリに含めるべきかしら。

`README.md` や `DEVELOP.md` とかに「アドバイス各種を書いておく」くらいがいい気がします。各々に合った方法を選んでもらえるように。

リポジトリの root はシンプルが良い派と、root でリポジトリのクオリティが計り知れる派がいると思うので、それも難しいところですが。

要 Docker ですが index.html と同じ階層で 👇 を叩けば `http://localhost:8888/` でアクセスできます。リポジトリにファイル追加なしで検証できます。

```bash
docker run --rm -d -v $(pwd):/www -p 8888:80 fnichol/uhttpd
```

また、上記で localhost のサーバを立ち上げておいて、 SSH で 👇を叩くと、`https://?????.localhost.run/` で外部サーバーとしての挙動も検証できます。

```bash
ssh -R 80:localhost:8888 ssh.localhost.run
```

**Comment by yumetodo** [comment]
環境構築ファイルってpackage.jsonへの追記だけで完結しますが・・・？

**Comment by yume-yu** [comment]
自分もこれについては反対派で、
> 環境構築ファイルが...

というのは本質ではないと思います。
自分の理解が正しければ、現状`package.json`はCIのために置かれたものであって、それ以外はnodeを必要としていません。そのため、ここで開発環境にnodeを必要とする方針に切り替える必要は今はないと思うのです。
この問題自体は @KEINOS さんが書かれたようにWebサーバーを自前で建てるほう方を案内し、それを使って開発中のプレビューをするようにすることで解決できると思います。

**Comment by KEINOS** [comment]
> @yumetodo 
> 環境構築ファイルってpackage.jsonへの追記だけで完結しますが・・・？

あ、いらないという意味で言っているのではなく「`npm` が使えない人お断り」な流れになっている気がするのです。

[editorconfig](https://editorconfig.org/) のように汎用なものならいいのですが、なんか「VS Code の設定ファイルまで置こうぜ！」的なニュアンスというか。

このリポジトリは「HTML, CSS, Javascript が読めれば参加できる」というのが強みなので、PR 時の運営側の軽減として CI を置いているだけで、それ以上はどうかなぁと思って。

でも、わかっている人には「用意しておきました」的なものがあると「お、お前わかってんじゃん」というのもわかります。ふーむ

**Comment by yumetodo** [comment]
まあ、主目的はlocalにサーバー立ててデバッグしよう、ということなのでまあ手段はそこまでこだわりないです

ただ、方法を固定した方がドキュメント書きやすいのかなと思ってました。

**Comment by KEINOS** [comment]
> ただ、方法を固定した方がドキュメント書きやすいのかなと思って

お気遣いあざっす！確かにローカルにサーバーを立てるのはデバッグにかなり有効なので、CONTRIBUTA.md に "Development TIPS" 項目を入れるとかどうでしょう？

そこにみんなで TIPS を追加してく、みたいな。PHP とか Docker とかも含めて。

**Comment by KEINOS** [comment]
Draft PR #64 の「開発時の TIPS」に関するガイドラインの進捗です。この方向でよければ、この Issue は close でいかがでしょう？ > @yumetodo 

- [コミット89f051c の CONTRIBUTING.md ](https://github.com/hidao80/mastogetter/blob/89f051cf9b23f292057e906e483f7f1c5cf00e57/CONTRIBUTING.md#%E9%96%8B%E7%99%BA%E6%99%82%E3%81%AE-tips)

**Comment by yumetodo** [comment]
方針は決したように思います。

**Comment by sasanquaneuf** [comment]
これそういえばcloseしちゃったので超今更ですけど、別にnode使わなくてよい前提で、
`npm run start` 的な奴は入れてもよかったかなと思っていました。（特にnode前提になって迷惑がかかるわけではなかったので）
みんなどうやってテストやってるんだろう

**Comment by yumetodo** [comment]
自分は

```bash
npm i -g koko
```

してる環境で生活しているので、単に`koko -o`してます

**Comment by yumetodo** [comment]
余談ですが`@js-primer/local-server`はアクセスログを表示してくれる点で面白いのでぜひ一度触ってみてください。

**Comment by sasanquaneuf** [comment]
なるほど、connection closed before res end/flush とか出るんですね
pythonのhttp.serverとかはよくつかっています
