### ISSUE TITLE
モバイルデバイス画面対応

### ISSUE THREAD

**Issue by hidao80** [hidao80/mastogetter#8]
リンク URL が長いとき、改行されず画面外まで文字列が伸びてしまう不具合があります。

**Comment by yume-yu** [comment]
リンクと画像のはみ出し、対応できたかんじがします

https://github.com/yume-yu/mastogetter/commit/14bf56c53c930f080ae2fb93f8156d29eac81e2a

**Comment by hidao80** [comment]
@yume-yu おおー！ いい感じに改行されていますね！
パーマリンク作成に関しては、こちらの方で修正していましたので pull するタイミングによってうまく動いていなかったかもしれません。🙇‍♂️

早速ブランチ切りますね！　ありがとうございます！
